# Generated by Django 4.0.2 on 2023-01-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='threshold',
            field=models.IntegerField(default=120),
        ),
    ]
